### ISSUE TITLE
BulletProof implementation issue

### ISSUE THREAD

**Issue by niconiconi** [hyraxZK/bccgp#1]
Traceback (most recent call last):

  File "run_bccgp.py", line 185, in <module>
    main()
  File "run_bccgp.py", line 174, in main
    run_bccgp()
  File "run_bccgp.py", line 84, in run_bccgp
    proof = prv.run({})
  File "/data/hyraxZK/bccgp/libbccgp/bullet.py", line 227, in run
    wcom = self.witness_commit(ai, bi, ci)
  File "/data/hyraxZK/bccgp/libbccgp/bullet.py", line 99, in witness_commit
    com_AI = self.gops.pow_gih(chain(aL, repeat(0, nRnd - self.n), aR), self.alpha, 0, nRnd + self.n)
  File "/data/hyraxZK/bccgp/pymiracl/__init__.py", line 202, in pow_gih
    return self.return_point(mircffi.pymr_pow_gih(arg, length, '%x'%valh, gi))
  File "/data/hyraxZK/bccgp/pymiracl/__init__.py", line 120, in return_point
    raise RuntimeError(ffi.string(mircffi.pymr_get_error()))
RuntimeError: Tried to use gi beyond end of list

I run the bulletproof by `python run_bccgp.py -p test.pws -b -c =4 -C m191`

and generate test.pws by `./pwsrepeat ../pws/experiments/SHA256/SHA256_64.pws 4
`

**Comment by niconiconi** [comment]
btw I also tried some other combinations and it will always return the same error message
